.Dd $Mdocdate$
.Dt PIE 1
.\".Os
.Sh NAME
.Nm pie
.Nd draws a pie chart in SVG format
.Sh SYNOPSIS
.Nm
.Op Fl t Ar title
.Op Fl d Ar description
.Op Fl w Ar width
.Op Fl h Ar height
.Op Fl o Ar outputfile
.Ar num ...
.Sh DESCRIPTION
The
.Nm
utility draws a pie chart from the given numbers.
.\" .Sh IMPLEMENTATION NOTES
.\" Not used in OpenBSD.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, & 9 only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, & 8 only.
.\" .Sh FILES
.Sh EXIT STATUS
.Ex -std
.\" For sections 1, 6, & 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, & 8 only.
.\" .Sh ERRORS
.\" For sections 2, 3, & 9 only.
.Sh SEE ALSO
.Xr gnuplot 1
.\" .Xr foobar 1
.\" .Sh STANDARDS
.\" .Sh HISTORY
.Sh AUTHORS
The
.Nm 
program was written by
.An Jan Klemkow Aq j.klemkow@wemelug.de .
.\" .Sh CAVEATS
.\" .Sh BUGS
.\" .Sh SECURITY CONSIDERATIONS
.\" Not used in OpenBSD.
