.Dd $Mdocdate$
.Dt PIE 1
.Sh NAME
.Nm pie
.Nd draws a pie chart in SVG format
.Sh SYNOPSIS
.Nm
.Op Fl t Ar title
.Op Fl d Ar description
.Op Fl w Ar width
.Op Fl h Ar height
.Op Fl o Ar outputfile
.Ar num ...
.Sh DESCRIPTION
The
.Nm
utility draws a pie chart from the given numbers.
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr gnuplot 1
.Sh AUTHORS
The
.Nm 
program was written by
.An Jan Klemkow Aq j.klemkow@wemelug.de .
